---
- name: EXECUTE NETWORK DEVICE CONFIGURATIONS FOR SCOPE B
  hosts: CSR1kv
  gather_facts: false
  connection: local
  tasks:
    - name: RUN INTERFACE AND ROUTING TASKS
      import_tasks: tasks_interface_routing.yml

    - name: RUN SECURITY AND BANNER TASKS
      import_tasks: tasks_security.yml