---
- name: CONFIGURE LOCAL USER ACCOUNT
  ios_config:
    lines:
      - username netops privilege 15 secret SecurePassword123

- name: CONFIGURE LOGIN BANNER MESSAGE
  ios_config:
    lines:
      - banner motd ^C AUTHORIZED ACCESS ONLY. ALL ACTIVITIES ARE LOGGED. ^C